### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by abalter** [chronitis/ipyrmd#3]
Is this a known issue?

```
bicb199:~ balter$ pip install ipyrmd
Collecting ipyrmd
  Using cached ipyrmd-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qm/b_1n3bn15wb373zvkvd1vcp4yjd86m/T/pip-build-2a0wfmi1/ipyrmd/setup.py", line 6, in <module>
        with open("README.md") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qm/b_1n3bn15wb373zvkvd1vcp4yjd86m/T/pip-build-2a0wfmi1/ipyrmd/
bicb199:~ balter$ pip3 isntall ipyrmd
ERROR: unknown command "isntall" - maybe you meant "install"
bicb199:~ balter$ pip3 install ipyrmd
Collecting ipyrmd
  Using cached ipyrmd-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/qm/b_1n3bn15wb373zvkvd1vcp4yjd86m/T/pip-build-aa0y07y2/ipyrmd/setup.py", line 6, in <module>
        with open("README.md") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qm/b_1n3bn15wb373zvkvd1vcp4yjd86m/T/pip-build-aa0y07y2/ipyrmd/
bicb199:~ balter$ 
```

**Comment by chronitis** [comment]
Thanks for reporting this.

Fixed in v0.4.2 (now on pypi).
